      - name: Run DetectionPulse AI

        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AI_TOKEN: ${{ secrets.AI_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}

        run: |

          echo "Starting DetectionPulse"

          ls -la

          ls -la database || true

          python -m src.main